### ISSUE TITLE
portfolio fingerprints: % matches, % tests that pass?

### ISSUE THREAD

**Issue by fscelliott** [sensible-hq/sensible-docs#211]
some lingering questions:

- is this true?
`If you specify a Match array in this parameter, then Sensible must find all the matches in the array on the same page for the test to pass.
If you want to specify fallback matches for the same page type, specify the matches in separate tests. For example, a form has revisions 1 and 2 that have slightly different wordings on the first page. Specify one test with a first page type and wording A, and specify a second test with a first page type and wording B.`

- TODO: is this true for all page types not just first page type? 

`"Specifies the text to match for the test.<br/>If you specify a Match array in this parameter, then Sensible must find all the matches in the array on the same page for the test to pass.<br/>If you want to specify fallback matches for the same page type, specify the matches in separate tests. For example, a form has revisions 1 and 2 that have slightly different wordings on the first page. Specify one test with a `first` page type and wording A, and specify a second test with a `first` page type and wording B."`

- TODO: in single-document fingerprints, how does a test 'pass' if it's a match array?

- TODO: How does a test "passes" for Portfolios? Is the following quote true?  (if so, add to fingerprint-mode and add a reference to 'more info about defining passing' in the fingerprint.md topic)

`"Sensible must find 100% of all matches in all tests to segment a document."`

**Comment by horacio-penya** [comment]
I'm giving this a look, but it's much more complex than I expected it to be (and I wrote a good bunch of that code 😬)

**Comment by horacio-penya** [comment]
At the start, every fingerprint is normalized as a `StandarizedFingerPrintMatch` (this should not be shown to the customers but will make my description easier) That means that each fingerprint will have a `{ match: Matcher[][] }` field.

In particular, strings are converted into `[ { type: "includes", text: match } ]` and single matchers are converted into `[ match ]`.

Then, our `StandardizedConfiguration` will have something like:

```
{
  fingerprint: {
      tests: [
        {
          page: "first",
          match: [
              [ { type: "includes", text: "A"}, {type: "equals", text: "B"}, ... ],
              [ ... ],
            ]
        },
        {
          page: "last",
          match: [
              [ ... ],
              [ ... ],
            ]
        },
        ...
      ]
    }
}

```
On configurations designed to be used with single doc extractions the tests array will have only one item.

Each matcher array (each item inside the match array, we could use a name for them) is looking for just one line in the document, in the example given, the first one means "search something that includes A and then some line that's exactly B".

For single doc extractions:

- we discard all the page/offset information and get all the Matcher arrays from the fingerprints together.

- we evaluate every Matcher array and if at least 50% of those match something in the document, we decide the document is of the right type.



For portfolio extractions:

- we split the document in pages

- for each page, and for each fingerprint (each item inside the tests array) we evaluate the matcher array and if every matcher array inside it matches, we consider the fingerprint to have matched that page and we store it in the results (to be used later to split the doc in subdocuments)



Some consequences of these different processes are:

- matcher arrays that go over page limits will work on single extractions but not on portfolio ones (if there is "A" in page 1 and "B" in page 2, the first fingerprint will match on single doc extractions, not on portfolio ones)

- if one matcher array from the first fingerprint and one from the second one match, the document will match when doing single doc extraction but no page will match when doing portfolio extractions (as the 100% of the matcher arrays from a fingerprint need to match for portfolios)

**Comment by fscelliott** [comment]
wow, I'm finally returning to this now. It's very complex, probably more complex than I want to expose the user to. 

I didn't COMPLETELY follow your explanations (I think there's some ambiguity around matchers in a match array and fingerprints vs tests)

but I tried to write out the following, is it correct?

```
Portfolio fingerprints differ from single-file document fingerprints in the following behaviors:

- If you specify a Match array in a test, then Sensible must find all the matches in the array on the same page in the portfolio for the test to pass and for Sensible to identify a page as "first", "last", or another type. In single-file documents, matches can occur anywhere in a document.
- Sensible must find 100% of all matches in all tests to segment a document in a portfolio. In single-file documents, Sensible must find 50% of all matches anywhere in the document by default to give the document a "passing" score.
- If you want to specify fallback matches for the same page type, specify the matches in separate tests. For example, a form has revisions 1 and 2 that have slightly different wordings on the first page. Specify one test with a `first` page type and wording A, and specify a second test with a `first` page type and wording B.
```
